// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourJarvis.Infrastructure.DataAccess.EfCoreDa;

namespace YourJarvis.Infrastructure.Migrations
{
    [DbContext(typeof(YourJarvisContext))]
    [Migration("20200131142212_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YourJarvis.ApplicationCore.Entities.Alan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Alans");
                });

            modelBuilder.Entity("YourJarvis.ApplicationCore.Entities.ArticleAggregate.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlanId")
                        .HasColumnType("int");

                    b.Property<string>("ArticleBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArticleDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArticleDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArticleStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ArticleViewCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOpenForComment")
                        .HasColumnType("bit");

                    b.HasKey("ArticleId");

                    b.HasIndex("AlanId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("YourJarvis.ApplicationCore.Entities.ArticleAggregate.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("YourJarvis.ApplicationCore.Entities.ArticleAggregate.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("YourJarvis.ApplicationCore.Entities.Alan", b =>
                {
                    b.HasOne("YourJarvis.ApplicationCore.Entities.Alan", "Parent")
                        .WithMany("AlanChilds")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("YourJarvis.ApplicationCore.Entities.ArticleAggregate.Article", b =>
                {
                    b.HasOne("YourJarvis.ApplicationCore.Entities.Alan", "Alan")
                        .WithMany("Articles")
                        .HasForeignKey("AlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourJarvis.ApplicationCore.Entities.ArticleAggregate.ArticleTag", b =>
                {
                    b.HasOne("YourJarvis.ApplicationCore.Entities.ArticleAggregate.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourJarvis.ApplicationCore.Entities.ArticleAggregate.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
